coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: 60%
    project:
      default:
        target: auto
        threshold: 0.1%
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    # after_n_builds should match the number of CI jobs configured to upload reports to Codecov
    # as of #1365, there are 2 such jobs, one each for the mpi4py-tests.yml and checks.yml workflows
    after_n_builds: 2
