name: watertap-reaktoro
channels:
  - conda-forge
dependencies:
  - cyipopt
  - reaktoro
  - ipopt
  - autodiff
  - chemicalfun
  - optima
  - phreeqc4rkt
  - reaktplot
  - thermofun

  # --- Python ---
  - python>=3.10,<3.14
  - pip

  - pip:
    - --editable ".[dev]"