name: watertap-reaktoro
channels:
  - conda-forge
dependencies:
  # ONLY what pip cannot provide
  - cyipopt
  - reaktoro
  - autodiff
  - chemicalfun
  - optima
  - phreeqc4rkt
  - reaktplot
  - thermofun
  - python>=3.10,<3.14
  - pip

  - pip:
    - --editable ".[dev]"