name: watertap-reaktoro

channels:
  - conda-forge

dependencies:
  # core language
  - python>=3.10,<3.12

  # conda only packages
  - reaktoro=2.13.0
  - cyipopt=1.6.1
  - ipopt=3.14.19
  - autodiff=1.1.2
  - chemicalfun=0.1.13
  - thermofun=0.6.1
  - optima=0.6.0
  - phreeqc4rkt=3.6.2.2
  - reaktplot=0.4.1
  - ampl-asl=1.0.0
  - metis=5.1.0
  - mumps-seq=5.8.2
  - eigen=3.4.0
  - pybind11=2.13.6
  - nlohmann_json=3.12.0
  - fmt=12.1.0
  - spdlog=1.17.0
  - yaml-cpp=0.8.0
  - multipledispatch=0.6.0

  # Jupyter environment
  - ipykernel
  - ipython
  - jupyterlab
  - notebook
  - ipywidgets

  # other required packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - h5py
  - sympy
  - networkx
  - plotly
  - pyyaml
  - packaging
  - pip

  - pip:
    # watertap project dependencies
    - pyomo==6.10.0
    - idaes-pse>=2.11.0rc0

    # watertap ecosystem dependencies
    - watertap-solvers==24.12.9
    - parameter-sweep==0.1.0+g54e62c4ba
    - reaktoro-pse @ git+https://github.com/watertap-org/reaktoro-pse.git  # update to release when available

    # editable install
    - -e .