#!/bin/bash

set -e
idaes get-extensions --verbose --distro ubuntu2204
python -c "import idaes; from pyomo.environ import SolverFactory as S; print(S('ipopt').executable())"
python -m ipykernel install --user --name watertap-dev
jupyter kernelspec list
jupyter kernelspec remove python3
jupyter kernelspec list